name: Release

on: push

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/') && github.event_name != 'pull_request'
    runs-on: windows-latest
    steps:
      - name: Create GitHub release
        uses: Roang-zero1/github-create-release-action@master
        with:
          version_regex: ^[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_release:
    if: startsWith(github.ref, 'refs/tags/') && github.event_name != 'pull_request'
    runs-on: windows-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install pyinstaller===5.6.2
        working-directory: ${{ github.workspace }}
      - run: pip install .
        working-directory: ${{ github.workspace }}
      - run: pyinstaller --onefile --noconsole -n sleepytime sleepytime/__main__.py
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: dist/sleepytime.exe



  pypi:
    runs-on: windows-latest
    needs: release
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
      - name: Build and publish
        working-directory: ${{ github.workspace }}
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python setup.py sdist bdist_wheel
          twine upload dist/*
